name: sentry
description: Crash detection and response MVP.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: any
  geolocator: any
  permission_handler: any
  path_provider: any
  intl: any
  shared_preferences: any
  google_fonts: any
  archive: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/diagrams.md
    - assets/report-template.md
    - assets/logo.png
